// ─── EMAIL OUTREACH LOG ────────────────────────────────────────────────────────
// Tracks every email sent from roborns@codelude.com via Resend.
// Auto-generated by Lisa. Updated on each send.

export interface EmailLogEntry {
  id: string;
  date: string;
  to: string;
  subject: string;
  status: 'sent' | 'opened' | 'clicked' | 'bounced' | 'replied';
  category: string;     // e.g. 'partner-intro', 'rfp', 'govt', 'investor'
  partnerName: string;  // which partner/contact
  notes: string;
}

export const EMAIL_LOG: EmailLogEntry[] = [
  // ── Initial Setup ──────────────────────────────────────────────────────────
  {
    id: 'EM-001',
    date: '2026-06-02',
    to: 'shawaz@codelude.com',
    subject: 'Test — Resend is live for Roborns',
    status: 'sent',
    category: 'internal',
    partnerName: 'System',
    notes: 'Resend API verification test. Domain codelude.com verified.',
  },
  {
    id: 'EM-002',
    date: '2026-06-02',
    to: 'shawaz@codelude.com',
    subject: '🎷 Test — Roborns email system live',
    status: 'sent',
    category: 'internal',
    partnerName: 'System',
    notes: 'Email pipeline fully operational. Resend API → roborns@codelude.com → shawaz@codelude.com (CC).',
  },
  {
    id: 'EM-003',
    date: '2026-06-03',
    to: 'sachidananda.salian@gmail.com',
    subject: 'Following up — Roborns coastal AI + desalination project, Mangaluru',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'KPT (Transmission)',
    notes: 'Intro email to Sachidananda re: 2MW HT grid connection guidance + property selection in Mangalore. Resend ID: 1930d22f-37f0-4073-acc2-8fdf0654d46c.',
  },
  {
    id: 'EM-004',
    date: '2026-06-03',
    to: 'wabag@wabag.in',
    subject: 'Request for Proposal — MED-TVC Desalination Skid — Roborns Mangaluru Project',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'VA Tech Wabag',
    notes: 'MED-TVC 50K L/day skid RFP sent. Resend ID: 6d04929b-613b-46af-8b84-dc98627256d0.',
  },
  {
    id: 'EM-005',
    date: '2026-06-03',
    to: 'info@greenkogroup.com',
    subject: 'PPA Inquiry — 2MW Wind + Solar for Roborns Coastal Project, Mangaluru',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Greenko / ReNew Power',
    notes: '2MW hybrid wind+solar PPA inquiry sent. Resend ID: dc0f9c1c-1723-4d86-9cd7-93ffcf40360a.',
  },
  {
    id: 'EM-006',
    date: '2026-06-03',
    to: 'corporatecommunications@afcons.com',
    subject: 'Coastal Site Survey RFP — Roborns AI + Desalination Project, Mangaluru',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Afcons Infrastructure',
    notes: 'Coastal site survey RFP sent. Resend ID: 343b1156-41f1-4890-bee9-63d3275bda14.',
  },
  {
    id: 'EM-007',
    date: '2026-06-03',
    to: 'rosz.bng-mef@nic.in',
    subject: 'CRZ Clearance Pathway Inquiry — Roborns Coastal Project, Mangaluru',
    status: 'sent',
    category: 'government',
    partnerName: 'KCZMA (via MoEFCC Bengaluru RO)',
    notes: 'CRZ clearance pathway inquiry sent to MoEFCC Regional Office Bengaluru. Resend ID: 27b79a57-9273-4125-8f1d-34750c145fdf.',
  },
  {
    id: 'EM-008',
    date: '2026-06-14',
    to: 'sales.apac@submer.com',
    subject: 'RFQ — 2MW Single-Phase Immersion Cooling — Roborns (DIFC HoldCo)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Submer Technologies',
    notes: '2MW single-phase immersion RFQ sent to Submer APAC. Resend ID: 46bf0f50-d80a-476e-9a40-66bd790cfa79.',
  },
  {
    id: 'EM-009',
    date: '2026-06-14',
    to: 'info@sterlingwilson.com',
    subject: 'RFQ — Electrical/MEP Fit-Out for 2MW AI Datacenter — Roborns (DIFC HoldCo)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Sterling & Wilson DC',
    notes: 'Building A electrical/MEP fit-out RFQ sent. Resend ID: 7c9619d7-0353-4d0e-a2f7-34a4dfd477b5.',
  },
  {
    id: 'EM-010',
    date: '2026-06-14',
    to: 'info@refroid.com',
    subject: 'RFQ — 2MW Single-Phase Immersion Cooling — Roborns (DIFC HoldCo)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Refroid Technologies',
    notes: '2MW single-phase immersion RFQ sent to Refroid. Tanks, CDUs, BPCL fluid, commissioning scope. Resend ID: 373b2319-9059-473b-bc47-c7f3d406beeb.',
  },
  // ── Jun 16 Batch — Follow-ups & Cold Intros ────────────────────────────────
  {
    id: 'EM-011',
    date: '2026-06-16',
    to: 'wabag@wabag.in',
    subject: 'Roborns — NDA & Next Steps Following Our Call (Jun 11)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'VA Tech Wabag',
    notes: 'Follow-up to Jun 11 meeting — NDA request + civil/Building B/Building C quotes. Resend ID: 9b5920fb-cc75-4159-8683-64b21319bede.',
  },
  {
    id: 'EM-012',
    date: '2026-06-16',
    to: 'sachidananda.salian@gmail.com',
    subject: 'Roborns — Follow-Up on Property Leads',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'KPT (Transmission)',
    notes: 'Follow-up on 3 property leads (Jun 3). Resend ID: ef06ab57-937c-4b79-bccf-6a6af2f64623.',
  },
  {
    id: 'EM-013',
    date: '2026-06-16',
    to: 'info@greenkogroup.com',
    subject: 'Roborns — Follow-Up: 2MW PPA Inquiry',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Greenko / ReNew Power',
    notes: 'Follow-up on PPA inquiry sent Jun 3. Resend ID: 480afaf1-b0cb-4cc4-b1e4-116bdc5daa6b.',
  },
  {
    id: 'EM-014',
    date: '2026-06-16',
    to: 'corporatecommunications@afcons.com',
    subject: 'Roborns — Follow-Up: Coastal Site Survey RFP',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Afcons Infrastructure',
    notes: 'Follow-up on site survey RFP sent Jun 3. Resend ID: c53b4cb8-f8f6-4356-8759-a1d93a2d3b44.',
  },
  {
    id: 'EM-015',
    date: '2026-06-16',
    to: 'rosz.bng-mef@nic.in',
    subject: 'Roborns — Follow-Up: CRZ Clearance Pathway Inquiry',
    status: 'sent',
    category: 'government',
    partnerName: 'KCZMA (via MoEFCC Bengaluru RO)',
    notes: 'Follow-up on CRZ inquiry sent Jun 3. Resend ID: baec45da-3446-4906-aba8-326e8ee8f0d2.',
  },
  {
    id: 'EM-016',
    date: '2026-06-16',
    to: 'nventures@nvidia.com',
    subject: 'Roborns — AI Compute Colocation Partnership — Mangaluru, India',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'NVIDIA (AI Compute)',
    notes: 'Cold intro to NVentures — colocation partnership / NPN program. Resend ID: ab0a7306-1bc1-4efb-8ba6-d32ae61dc73b.',
  },
  {
    id: 'EM-017',
    date: '2026-06-16',
    to: 'tanuj@e2enetworks.com',
    subject: 'Roborns — Colocation Partnership — 2MW AI DC (Mangaluru)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'E2E Networks',
    notes: 'Cold intro to CEO Tanuj — colocation LOI discussion. Resend ID: 9c3ee7ee-cfc3-4f78-8ce4-e4db879d7864.',
  },
  {
    id: 'EM-018',
    date: '2026-06-16',
    to: 'basicchem@tatachemicals.com',
    subject: 'Roborns — Mg(OH)₂ Offtake Proposal — Mangaluru Project',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Tata Chemicals',
    notes: 'Cold intro — Mg(OH)₂ offtake MoU proposal. Resend ID: 0862fa18-7271-4ceb-bf3f-862ffdfc76ef.',
  },
  {
    id: 'EM-019',
    date: '2026-06-16',
    to: 'power@alfalaval.com',
    subject: 'Roborns — Titanium PHE Quote Request — Waste Heat Recovery (2MW)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Alfa Laval India',
    notes: 'Cold intro — titanium PHE quote for waste heat recovery. Resend ID: 531571fb-3afe-4b5f-ad2b-a0c3523be997.',
  },
  {
    id: 'EM-020',
    date: '2026-06-16',
    to: 'consult@thermaxglobal.com',
    subject: 'Roborns — Waste Heat Recovery Study — 2MW AI Datacenter',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Thermax India',
    notes: 'Cold intro — waste heat recovery study for immersion cooling + MED-TVC integration. Resend ID: da5a3f30-fcd1-4e80-b5d3-44cabe5347c2.',
  },
  {
    id: 'EM-021',
    date: '2026-06-16',
    to: 'sales@liquidstack.com',
    subject: 'Roborns — Immersion Cooling RFQ — 2MW Datacenter (Mangaluru)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'LiquidStack / GRC',
    notes: 'Cold intro — immersion cooling RFQ (backup to Submer/Refroid proposals). Resend ID: 162d6cce-050b-41b4-b5ad-4a788959ea52.',
  },
  {
    id: 'EM-022',
    date: '2026-06-16',
    to: 'rahul.ghumatkar@sterlingandwilsondc.com',
    subject: 'Re: RFQ — Electrical/MEP Fit-Out for 2MW AI Datacenter — Roborns (DIFC HoldCo)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Sterling & Wilson DC',
    notes: 'Reply to Rahul Ghumatkar (VP BD, ME) — shared mobile +91 8884449055 to proceed. Resend ID: 5e525b81-1ff0-42f7-bf73-06591675882b.',
  },
  {
    id: 'EM-024',
    date: '2026-06-23',
    to: 'wabag@wabag.in',
    subject: 'Roborns — Quotation Scope & Desal Co-Location (Follow-Up to Our Call)',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'VA Tech Wabag',
    notes: 'Second call follow-up. Sent scope docs (roborns-wabag-quote.ts, roborns-desal-colocation.ts). Resend ID: 8b891ece-9c9c-425d-ae50-084df7f3eaff.',
  },
];

// ─── OUTREACH SEQUENCES ───────────────────────────────────────────────────────
// Ordered list of target partners for the current outreach phase.

export interface OutreachStep {
  id: string;
  priority: 1 | 2 | 3;
  partner: string;
  contactEmail: string;
  category: string;
  purpose: string;
  templateRef: string;
  status: 'draft' | 'ready' | 'sent' | 'followup' | 'replied' | 'meeting' | 'closed';
}

export const OUTREACH_PIPELINE: OutreachStep[] = [
  // Tier 1 — Critical path (needed for govt/investor pitch)
  { id: 'O-001', priority: 1, partner: 'VA Tech Wabag',     contactEmail: 'wabag@wabag.in',          category: 'Desalination', purpose: 'Second meeting 2026-06-23 (Mayank Mani Prasad). Quotes requested: 2/5/10/20MW civil + MED + ZLD. Also: desal co-location strategy for KSA/India. See roborns-wabag-quote.ts and roborns-desal-colocation.ts', templateRef: 'rfp-med',   status: 'meeting' },
  { id: 'O-002', priority: 1, partner: 'KPT (Transmission)', contactEmail: 'sachidananda.salian@gmail.com', category: 'Energy', purpose: '2MW HT grid connection + property selection in Mangalore (via Sachidananda)', templateRef: 'mescom-ht', status: 'followup' },
  { id: 'O-003', priority: 1, partner: 'Greenko / ReNew',   contactEmail: 'info@greenkogroup.com',  category: 'Energy',       purpose: 'Wind+solar PPA inquiry',        templateRef: 'ppa-inquiry', status: 'followup' },
  { id: 'O-004', priority: 1, partner: 'Afcons Infra',      contactEmail: 'corporatecommunications@afcons.com', category: 'Construction', purpose: 'Coastal site survey RFP', templateRef: 'site-rfp', status: 'followup' },
  { id: 'O-005', priority: 1, partner: 'Karnataka Coastal Authority', contactEmail: 'rosz.bng-mef@nic.in', category: 'Government', purpose: 'CRZ clearance pathway inquiry (via MoEFCC Bengaluru RO)', templateRef: 'govt-crz',  status: 'followup' },

  // Tier 2 — Anchor tenant LOIs
  { id: 'O-006', priority: 2, partner: 'NVIDIA (AI Compute)', contactEmail: 'nventures@nvidia.com',       category: 'Servers',      purpose: 'Compute colocation intro — NVentures investment / NPN colo partnership',      templateRef: 'colo-intro', status: 'sent' },
  { id: 'O-007', priority: 2, partner: 'E2E Networks',      contactEmail: 'tanuj@e2enetworks.com',    category: 'Servers',      purpose: 'Colocation LOI discussion — direct to CEO',     templateRef: 'colo-intro', status: 'sent' },
  { id: 'O-008', priority: 2, partner: 'Tata Chemicals',    contactEmail: 'basicchem@tatachemicals.com',  category: 'Minerals',     purpose: 'Mg(OH)₂ offtake MoU — Basic Chemistry division',          templateRef: 'offtake-intro', status: 'sent' },

  // Tier 3 — Technology vendors (post-RFP)
  { id: 'O-009', priority: 3, partner: 'Alfa Laval India',  contactEmail: 'power@alfalaval.com',      category: 'Thermal',      purpose: 'Titanium PHE quote request — waste heat recovery',    templateRef: 'thermal-rfp', status: 'sent' },
  { id: 'O-010', priority: 3, partner: 'Thermax India',     contactEmail: 'consult@thermaxglobal.com',        category: 'Thermal',      purpose: 'Waste heat recovery study — Projects & Consulting div',     templateRef: 'thermal-rfp', status: 'sent' },
  { id: 'O-011', priority: 3, partner: 'LiquidStack / GRC', contactEmail: 'sales@liquidstack.com',    category: 'Immersion',   purpose: 'Immersion tank RFQ (backup to Submer/Refroid)', templateRef: 'immersion-rfq', status: 'sent' },

  // Building-wise partner outreach (Partner_Map_Outreach.md, 2026-06-12)
  { id: 'O-012', priority: 1, partner: 'Refroid Technologies', contactEmail: 'info@refroid.com',    category: 'Immersion',    purpose: '2MW single-phase immersion RFQ — tanks, CDUs, BPCL fluid terms, >1MW references (website form + email)', templateRef: 'immersion-rfq', status: 'sent' },
  { id: 'O-013', priority: 1, partner: 'Submer Technologies',  contactEmail: 'sales.apac@submer.com',    category: 'Immersion',    purpose: '2MW single-phase immersion RFQ — tanks, CDUs, fluid, commissioning; water-side scope boundary', templateRef: 'immersion-rfq', status: 'sent' },
  { id: 'O-014', priority: 1, partner: 'Sterling & Wilson DC', contactEmail: 'rahul.ghumatkar@sterlingandwilsondc.com',    category: 'Construction', purpose: 'Building A electrical/MEP fit-out budgetary quote (2MW, no chiller plant); substation + HT cable optional', templateRef: 'dc-fitout-rfq', status: 'replied' },
  { id: 'O-015', priority: 2, partner: 'Thermax India',        contactEmail: 'tbd@thermax.com',     category: 'Minerals/ZLD', purpose: 'Building C ZLD RFQ — Phase 1 NaCl-only crystallization on MED brine, EPC and EPC+O&M', templateRef: 'zld-rfq', status: 'draft' },
  { id: 'O-016', priority: 2, partner: 'Praj Industries',      contactEmail: 'tbd@praj.net',        category: 'Minerals/ZLD', purpose: 'Building C ZLD RFQ — same spec as Thermax for comparison', templateRef: 'zld-rfq', status: 'draft' },
  { id: 'O-017', priority: 3, partner: 'BARC',                 contactEmail: 'tbd@barc.gov.in',     category: 'Desalination', purpose: 'MED-TVC technology transfer inquiry — terms, fees, approved fabricators', templateRef: 'barc-inquiry', status: 'draft' },

  // ── KSA Outreach Targets (added Jun 2026) ─────────────────────────────────────
  { id: 'O-018', priority: 1, partner: 'ACWA Power (via Riyadh partner)', contactEmail: '—', category: 'KSA Strategic', purpose: 'Strategic partnership one-pager — desal + immersion cooling synergy (✓ drafted: docs/ACWA-Power-One-Pager.md)', templateRef: 'ksa-intro', status: 'draft' },
  { id: 'O-019', priority: 1, partner: 'PIF Tech Portfolio', contactEmail: '—', category: 'KSA Investor', purpose: 'PIF AI infrastructure investment — warm intro via partner network', templateRef: 'ksa-investor', status: 'draft' },
  { id: 'O-020', priority: 1, partner: 'MCIT AI Fund — Saudi MOCIT', contactEmail: '—', category: 'KSA Grant', purpose: 'MCIT National AI Strategy grant application', templateRef: 'ksa-grant', status: 'draft' },
  { id: 'O-021', priority: 2, partner: 'G42 Data Centers (Abu Dhabi)', contactEmail: '—', category: 'KSA Strategic', purpose: 'Middle East AI compute infrastructure partnership', templateRef: 'ksa-intro', status: 'draft' },
  { id: 'O-022', priority: 2, partner: 'SIDF — Saudi Industrial Dev Fund', contactEmail: '—', category: 'KSA Grant', purpose: 'Industrial loan application for KSA Phase 1 facility', templateRef: 'ksa-grant', status: 'draft' },
  { id: 'O-023', priority: 3, partner: 'Masdar (Abu Dhabi)', contactEmail: '—', category: 'KSA Strategic', purpose: 'Renewable PPA for zero-carbon KSA Roborns facility', templateRef: 'ksa-intro', status: 'draft' },
  { id: 'O-024', priority: 3, partner: 'SWCC — Saline Water Conversion Corp', contactEmail: '—', category: 'KSA Strategic', purpose: 'Desalination technology synergy inquiry', templateRef: 'ksa-intro', status: 'draft' },
  { id: 'O-025', priority: 1, partner: 'Dammam/Jubail Industrial Site (via brother)', contactEmail: '—', category: 'KSA Site', purpose: 'Site scoping — Eastern Province industrial zone survey', templateRef: '', status: 'draft' },

  // ── System Log (internal entries using OutreachStep shape) ─────────────────
  {
    id: 'EM-999',
    priority: 1 as const,
    partner: 'System (Financial model recalibrated)',
    contactEmail: 'sha.waz',
    category: 'internal',
    purpose: 'India Roborns model recalibrated (power ₹3.5/kWh PPA, colo ₹14K/kW/mo, water→byproduct, immersion ₹10 Cr). KSA scenario added (subsidized power, premium pricing, PIF/ACWA/MCIT targets, $4.5M raise). Updated tasks.ts (10 new KSA tasks), fundraising.ts (6 KSA investor leads, R4 round), fin-models.ts (dual entry).',
    templateRef: '',
    status: 'sent' as const,
  },
];
