// ─── EMAIL OUTREACH LOG ────────────────────────────────────────────────────────
// Tracks every email sent from roborns@codelude.com via Resend.
// Auto-generated by Lisa. Updated on each send.

export interface EmailLogEntry {
  id: string;
  date: string;
  to: string;
  subject: string;
  status: 'sent' | 'opened' | 'clicked' | 'bounced' | 'replied';
  category: string;     // e.g. 'partner-intro', 'rfp', 'govt', 'investor'
  partnerName: string;  // which partner/contact
  notes: string;
}

export const EMAIL_LOG: EmailLogEntry[] = [
  // ── Initial Setup ──────────────────────────────────────────────────────────
  {
    id: 'EM-001',
    date: '2026-06-02',
    to: 'shawaz@codelude.com',
    subject: 'Test — Resend is live for Roborns',
    status: 'sent',
    category: 'internal',
    partnerName: 'System',
    notes: 'Resend API verification test. Domain codelude.com verified.',
  },
  {
    id: 'EM-002',
    date: '2026-06-02',
    to: 'shawaz@codelude.com',
    subject: '🎷 Test — Roborns email system live',
    status: 'sent',
    category: 'internal',
    partnerName: 'System',
    notes: 'Email pipeline fully operational. Resend API → roborns@codelude.com → shawaz@codelude.com (CC).',
  },
  {
    id: 'EM-003',
    date: '2026-06-03',
    to: 'sachidananda.salian@gmail.com',
    subject: 'Following up — Roborns coastal AI + desalination project, Mangaluru',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'KPT (Transmission)',
    notes: 'Intro email to Sachidananda re: 2MW HT grid connection guidance + property selection in Mangalore. Resend ID: 1930d22f-37f0-4073-acc2-8fdf0654d46c.',
  },
  {
    id: 'EM-004',
    date: '2026-06-03',
    to: 'wabag@wabag.in',
    subject: 'Request for Proposal — MED-TVC Desalination Skid — Roborns Mangaluru Project',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'VA Tech Wabag',
    notes: 'MED-TVC 50K L/day skid RFP sent. Resend ID: 6d04929b-613b-46af-8b84-dc98627256d0.',
  },
  {
    id: 'EM-005',
    date: '2026-06-03',
    to: 'info@greenkogroup.com',
    subject: 'PPA Inquiry — 2MW Wind + Solar for Roborns Coastal Project, Mangaluru',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Greenko / ReNew Power',
    notes: '2MW hybrid wind+solar PPA inquiry sent. Resend ID: dc0f9c1c-1723-4d86-9cd7-93ffcf40360a.',
  },
  {
    id: 'EM-006',
    date: '2026-06-03',
    to: 'corporatecommunications@afcons.com',
    subject: 'Coastal Site Survey RFP — Roborns AI + Desalination Project, Mangaluru',
    status: 'sent',
    category: 'partner-intro',
    partnerName: 'Afcons Infrastructure',
    notes: 'Coastal site survey RFP sent. Resend ID: 343b1156-41f1-4890-bee9-63d3275bda14.',
  },
  {
    id: 'EM-007',
    date: '2026-06-03',
    to: 'rosz.bng-mef@nic.in',
    subject: 'CRZ Clearance Pathway Inquiry — Roborns Coastal Project, Mangaluru',
    status: 'sent',
    category: 'government',
    partnerName: 'KCZMA (via MoEFCC Bengaluru RO)',
    notes: 'CRZ clearance pathway inquiry sent to MoEFCC Regional Office Bengaluru. Resend ID: 27b79a57-9273-4125-8f1d-34750c145fdf.',
  },
];

// ─── OUTREACH SEQUENCES ───────────────────────────────────────────────────────
// Ordered list of target partners for the current outreach phase.

export interface OutreachStep {
  id: string;
  priority: 1 | 2 | 3;
  partner: string;
  contactEmail: string;
  category: string;
  purpose: string;
  templateRef: string;
  status: 'draft' | 'ready' | 'sent' | 'followup' | 'replied' | 'meeting' | 'closed';
}

export const OUTREACH_PIPELINE: OutreachStep[] = [
  // Tier 1 — Critical path (needed for govt/investor pitch)
  { id: 'O-001', priority: 1, partner: 'VA Tech Wabag',     contactEmail: 'wabag@wabag.in',          category: 'Desalination', purpose: 'MED-TVC 50K L/day skid RFP',   templateRef: 'rfp-med',   status: 'sent' },
  { id: 'O-002', priority: 1, partner: 'KPT (Transmission)', contactEmail: 'sachidananda.salian@gmail.com', category: 'Energy', purpose: '2MW HT grid connection + property selection in Mangalore (via Sachidananda)', templateRef: 'mescom-ht', status: 'sent' },
  { id: 'O-003', priority: 1, partner: 'Greenko / ReNew',   contactEmail: 'info@greenkogroup.com',  category: 'Energy',       purpose: 'Wind+solar PPA inquiry',        templateRef: 'ppa-inquiry', status: 'sent' },
  { id: 'O-004', priority: 1, partner: 'Afcons Infra',      contactEmail: 'corporatecommunications@afcons.com', category: 'Construction', purpose: 'Coastal site survey RFP', templateRef: 'site-rfp', status: 'sent' },
  { id: 'O-005', priority: 1, partner: 'Karnataka Coastal Authority', contactEmail: 'rosz.bng-mef@nic.in', category: 'Government', purpose: 'CRZ clearance pathway inquiry (via MoEFCC Bengaluru RO)', templateRef: 'govt-crz',  status: 'sent' },

  // Tier 2 — Anchor tenant LOIs
  { id: 'O-006', priority: 2, partner: 'NVIDIA (AI Compute)', contactEmail: 'tbd@nvidia.com',       category: 'Servers',      purpose: 'Compute colocation intro',      templateRef: 'colo-intro', status: 'draft' },
  { id: 'O-007', priority: 2, partner: 'E2E Networks',      contactEmail: 'tbd@e2enetworks.com',    category: 'Servers',      purpose: 'Colocation LOI discussion',     templateRef: 'colo-intro', status: 'draft' },
  { id: 'O-008', priority: 2, partner: 'Tata Chemicals',    contactEmail: 'tbd@tatachemicals.com',  category: 'Minerals',     purpose: 'Mg(OH)₂ offtake MoU',          templateRef: 'offtake-intro', status: 'draft' },

  // Tier 3 — Technology vendors (post-RFP)
  { id: 'O-009', priority: 3, partner: 'Alfa Laval India',  contactEmail: 'tbd@alfalaval.com',      category: 'Thermal',      purpose: 'Titanium PHE quote request',    templateRef: 'thermal-rfp', status: 'draft' },
  { id: 'O-010', priority: 3, partner: 'Thermax India',     contactEmail: 'tbd@thermax.com',        category: 'Thermal',      purpose: 'Waste heat recovery study',     templateRef: 'thermal-rfp', status: 'draft' },
  { id: 'O-011', priority: 3, partner: 'LiquidStack / GRC', contactEmail: 'tbd@liquidstack.com',    category: 'Immersion',   purpose: 'Immersion tank RFQ',            templateRef: 'immersion-rfq', status: 'draft' },
];
