// ─── POSITIONS ────────────────────────────────────────────────────────────────

export type PositionStatus = 'open' | 'on-hold' | 'closed';
export type PositionType   = 'Full-time' | 'Contract' | 'Part-time' | 'Advisory';

export interface Position {
  id:           string;
  title:        string;
  department:   string;
  venture:      string;
  type:         PositionType;
  status:       PositionStatus;
  priority:     'critical' | 'high' | 'medium';
  targetStart:  string;
  location:     string;
  phase?:       string;
  salaryRange?: string;
  keySkills:    string[];
  notes:        string;
}

export const POSITIONS: Position[] = [
  { id: 'P01', title: 'Thermal / Coastal Engineer', department: 'Roborns Engineering', venture: 'Roborns', type: 'Contract', status: 'open', priority: 'critical', targetStart: 'Q3 2026', location: 'Mangaluru / Remote', keySkills: ['Heat exchange systems', 'Coastal industrial construction', 'Desalination', 'Marine engineering', 'MED / MSF systems'], notes: 'First hire. Validates the entire Roborns technical model. Must have coastal heat exchange experience.' },
  { id: 'P02', title: 'Investment Platform Legal Counsel', department: 'Legal & Compliance', venture: 'Franchiseen', type: 'Contract', status: 'open', priority: 'critical', targetStart: 'Q3 2026', location: 'Remote / Delhi / Mumbai', keySkills: ['SEBI regulations', 'Investment platform compliance', 'Revenue-sharing structures', 'KYC/AML frameworks', 'Investor agreement drafting'], notes: 'External counsel for Franchiseen regulatory pathway. SEBI-familiar mandatory.' },
  { id: 'P03', title: 'Dubai HoldCo Legal Counsel', department: 'Legal & Compliance', venture: 'Codelude', type: 'Contract', status: 'open', priority: 'critical', targetStart: 'Q3 2026', location: 'Dubai (DIFC)', keySkills: ['DIFC / ADGM incorporation', 'Token structure and digital assets', 'UAE company law', 'Investment vehicle structuring', 'Smart contract legal review'], notes: 'DIFC-registered firm for HoldCo incorporation and token structure. Critical path for seed round.' },
  { id: 'P04', title: 'Full-Stack Engineer', department: 'Engineering', venture: 'Codelude', type: 'Full-time', status: 'open', priority: 'high', targetStart: 'Q4 2026', location: 'Mangaluru / Remote', keySkills: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'React'], notes: 'First full-time engineering hire. Will own HubCV and Franchiseen platform development.' },
  { id: 'P05', title: 'AI / ML Engineer', department: 'Engineering', venture: 'HubCV', type: 'Full-time', status: 'open', priority: 'high', targetStart: 'Q4 2026', location: 'Remote', keySkills: ['Python', 'LLM integration', 'Matching algorithms', 'Vector databases', 'NLP'], notes: 'Owns HubCV matching engine. LLM prompt engineering and skill graph development.' },
  { id: 'P06', title: 'Franchise Partnership Manager', department: 'Franchiseen Product', venture: 'Franchiseen', type: 'Full-time', status: 'open', priority: 'high', targetStart: 'Q4 2026', location: 'Mangaluru / Travel', keySkills: ['B2B sales', 'Franchise industry knowledge', 'Relationship management', 'Contract negotiation', 'Hindi/Kannada preferred'], notes: 'Owns franchise brand acquisition. Needs to sign 5+ brands in first 6 months.' },
  { id: 'P07', title: 'Hardware Product Manager', department: 'Engineering', venture: 'Cuestay', type: 'Full-time', status: 'on-hold', priority: 'medium', targetStart: 'Q1 2027', location: 'Remote / Mangaluru', keySkills: ['IoT hardware', 'Matter protocol', 'ODM/OEM management', 'Product specification', 'Supply chain'], notes: 'Owns Cuestay hub hardware. On hold until hardware manufacturing partner is signed.' },
  { id: 'P08', title: 'Marketing & Content Lead', department: 'Marketing & Brand', venture: 'Codelude', type: 'Full-time', status: 'open', priority: 'medium', targetStart: 'Q1 2027', location: 'Remote', keySkills: ['Content strategy', 'B2B marketing', 'SEO', 'Social media', 'Copywriting'], notes: 'Owns Codelude brand voice and all venture content. Investor-facing communications included.' },
  { id: 'P09', title: 'Deep-Tech Advisor — Infrastructure', department: 'Strategy & Finance', venture: 'Roborns', type: 'Advisory', status: 'open', priority: 'medium', targetStart: 'Q3 2026', location: 'Remote / Dubai', keySkills: ['Data center operations', 'Coastal infrastructure', 'Energy markets', 'Investor credibility', 'SE Asia / Gulf networks'], notes: 'Advisory role — adds credibility to Roborns for investor conversations. Equity or token compensation.' },

  // ─── ROBORNS OPERATIONS HEADCOUNT PLAN (8→15→22→28) ─────────────────────────
  // Y1 Pre-ops — hire Q3 2026 before construction completes (4 roles)
  { id: 'R01', title: 'Site Operations Manager',           department: 'Roborns Operations',    venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'critical', targetStart: 'Q3 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Pre-ops', salaryRange: '₹35–42L/yr', keySkills: ['Facility management', 'Industrial commissioning', 'Vendor coordination', 'CRZ / coastal permits', 'MESCOM liaison'], notes: 'First ops hire. Leads construction oversight, vendor management, and facility commissioning across all 3 buildings. Acts as site lead until senior engineering heads are onboarded in Y3–Y4.' },
  { id: 'R03', title: 'Electrical Engineer',               department: 'Roborns Engineering',   venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'critical', targetStart: 'Q3 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Pre-ops', salaryRange: '₹28–34L/yr', keySkills: ['HT grid connection', 'Industrial power distribution', 'UPS & ATS systems', 'Rooftop solar commissioning', 'MESCOM 10MW HT application'], notes: 'Owns the MESCOM 10MW HT connection, transformer station, redundant PDUs, ATS, and rooftop solar commissioning. Critical path item — must be on-site before grid energisation.' },
  { id: 'R04', title: 'Site Safety & CRZ Compliance Officer', department: 'Roborns Operations', venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'high',     targetStart: 'Q3 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Pre-ops', salaryRange: '₹10–13L/yr', keySkills: ['CRZ regulations', 'Environmental compliance', 'Industrial site safety', 'Permit management', 'Coastal Authority liaison'], notes: 'Ensures CRZ clearance conditions are met throughout construction and operations. Manages environmental compliance reports, safety protocols, and interface with Karnataka Coastal Authority.' },
  { id: 'R08', title: 'Admin & Finance Coordinator',       department: 'Roborns Operations',    venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'high',     targetStart: 'Q3 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Pre-ops', salaryRange: '₹7–9L/yr',   keySkills: ['Site administration', 'Vendor invoice processing', 'Petty cash & procurement', 'HR coordination', 'Tally / accounting basics'], notes: 'Handles day-to-day site admin, vendor payments, petty cash, permit document filing, and HR coordination for all on-site staff. Reports to Site Operations Manager.' },

  // Y1 Operations — hire Q4 2026, all 3 buildings live from day 1 (5 roles, cumulative 9)
  { id: 'R05', title: 'Data Centre Technician #1',         department: 'Roborns Compute',       venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'critical', targetStart: 'Q4 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Operations', salaryRange: '₹12–16L/yr', keySkills: ['Server rack installation', 'Structured cabling', 'KVM & IPMI', 'Immersion cooling systems', 'Incident response'], notes: 'First DC technician — installs and manages the 2MW immersion tank system (GRC / LiquidStack) and all rack-mounted compute hardware. Responsible for tenant rack handovers, cable management, and first-line incident resolution. Covers day shift.' },
  { id: 'R06', title: 'Desalination Plant Operator #1',   department: 'Roborns Water',         venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'critical', targetStart: 'Q4 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Operations', salaryRange: '₹8–11L/yr',  keySkills: ['MED / MVC plant operation', 'Water treatment processes', 'SCADA / PLC basics', 'Chemical dosing', 'Daily sampling and logging'], notes: 'Operates the VA Tech Wabag MED-TVC skid and associated seawater intake, heat exchanger pre-treatment, and distribution lines. Performs daily water quality checks, chemical dosing adjustments, and plant log entries.' },
  { id: 'R07', title: 'Water Quality & Lab Technician',   department: 'Roborns Water',         venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'high',     targetStart: 'Q4 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Operations', salaryRange: '₹7–9L/yr',   keySkills: ['Water quality testing (TDS, pH, turbidity)', 'Brine concentration analysis', 'Mineral sampling', 'ISO lab procedures', 'Report writing'], notes: 'Runs daily water quality tests across Building B output and Building C mineral streams. Maintains compliance records for municipal water offtake (KUWSDB) and tracks mineral concentration grades for Tata Chemicals / GHCL offtake quality.' },
  { id: 'R02', title: 'Thermal & Process Engineer',       department: 'Roborns Engineering',   venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'critical', targetStart: 'Q4 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Operations', salaryRange: '₹32–40L/yr', keySkills: ['Heat exchanger systems (Alfa Laval PHE)', 'MED distillation engineering', 'Immersion cooling thermodynamics', 'P&ID reading', 'Coastal process engineering'], notes: 'Permanent FT role after P01 contract validation phase. Owns the thermal loop — compute heat → Alfa Laval PHE → MED pre-heater → distillation. Also oversees Building C evaporator and crystallizer thermal performance. Day-to-day engineering lead for all process systems.' },
  { id: 'R10', title: 'Mineral Processing Technician',    department: 'Roborns Minerals',      venture: 'Roborns', type: 'Full-time', status: 'open',     priority: 'critical', targetStart: 'Q4 2026', location: 'Mangaluru (on-site)', phase: 'Y1 — Operations', salaryRange: '₹12–16L/yr', keySkills: ['Ion-exchange column operation (LANXESS Lewatit)', 'Brine concentration processes', 'Thermal crystallizer operation (HRS/SPX)', 'Product purity sampling', 'Chemical safety (Mg, KCl, Br)'], notes: 'Building C is live from Day 1 — all 3 buildings open together. This technician operates the ion-exchange columns, HRS crystallizer, and Praj ZLD evaporator from commissioning. Ensures daily mineral output meets Tata Chemicals and GHCL grade specifications from first production day.' },

  // Y2 Scale — hire Q1–Q3 2027 (+6, cumulative 15)
  { id: 'R09', title: 'Network & IT Engineer',            department: 'Roborns Compute',       venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q1 2027', location: 'Mangaluru (on-site)', phase: 'Y2 — Scale', salaryRange: '₹28–35L/yr', keySkills: ['Data centre networking (spine-leaf)', 'BGP / OSPF routing', 'Fibre & structured cabling', 'Tenant VLAN / cross-connect', 'Network monitoring (Grafana / Prometheus)'], notes: 'Designs and manages all data centre networking — tenant cross-connects, uplinks, BGP peering, and internal management network. Critical hire before 4MW second-phase tenant onboarding.' },
  { id: 'R11', title: 'Data Centre Technician #2',        department: 'Roborns Compute',       venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q2 2027', location: 'Mangaluru (on-site)', phase: 'Y2 — Scale', salaryRange: '₹12–16L/yr', keySkills: ['Server rack installation', 'Immersion cooling maintenance', 'Hardware troubleshooting', 'KVM / IPMI', 'Shift coverage'], notes: 'Second DC technician to enable shift rotation across the 4MW expanded system. Covers night shift or weekend shift alongside R05.' },
  { id: 'R12', title: 'Facilities Maintenance Engineer',  department: 'Roborns Operations',    venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q1 2027', location: 'Mangaluru (on-site)', phase: 'Y2 — Scale', salaryRange: '₹20–26L/yr', keySkills: ['Preventive maintenance planning', 'Pump and valve servicing', 'RO membrane replacement', 'Filter change-out (LANXESS, Ion Exchange India)', 'CMMS software'], notes: 'Owns scheduled and corrective maintenance across all 3 buildings — immersion fluid filters, MED pre-filters, RO membranes, seawater intake pumps, and ion-exchange resin regeneration cycles.' },
  { id: 'R13', title: 'Customer Success Manager (Compute)', department: 'Roborns Compute',     venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q2 2027', location: 'Mangaluru / Remote', phase: 'Y2 — Scale', salaryRange: '₹32–40L/yr', keySkills: ['Data centre colocation sales', 'SLA management', 'Tenant onboarding', 'Monthly reporting', 'NVIDIA / E2E Networks / Yotta relationship management'], notes: 'Owns colocation tenant relationships — onboarding, monthly SLA reporting, uptime dashboards, and escalation management. Primary contact for NVIDIA, E2E Networks, and Yotta Data Services accounts.' },
  { id: 'R14', title: 'Business Development Manager (Water & Minerals)', department: 'Roborns Sales', venture: 'Roborns', type: 'Full-time', status: 'on-hold', priority: 'high', targetStart: 'Q2 2027', location: 'Mangaluru / Travel', phase: 'Y2 — Scale', salaryRange: '₹38–46L/yr', keySkills: ['B2B industrial sales', 'Municipal water procurement', 'Chemical commodity offtake', 'Contract negotiation', 'Tata Chemicals / GHCL account management'], notes: 'Owns water and mineral revenue streams — manages KUWSDB municipal water offtake agreement, develops commercial water accounts, and handles NaCl / Mg(OH)₂ / KCl commodity offtake contracts with Tata Chemicals, GHCL, and Nirma.' },
  { id: 'R15', title: 'Desalination Plant Operator #2',   department: 'Roborns Water',         venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q3 2027', location: 'Mangaluru (on-site)', phase: 'Y2 — Scale', salaryRange: '₹8–11L/yr',  keySkills: ['MED plant operation', 'Shift handover procedures', 'Chemical dosing', 'SCADA monitoring', 'Emergency shutdown protocols'], notes: 'Second operator for 24/7 shift coverage as water output scales to 100K L/day. Ensures uninterrupted MED plant operation during shift changes and maintenance windows.' },

  // Y3 Growth — hire Q1–Q3 2028 (+7, cumulative 22)
  { id: 'R16', title: 'Head of Data Centre Operations',   department: 'Roborns Compute',       venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q1 2028', location: 'Mangaluru (on-site)', phase: 'Y3 — Growth', salaryRange: '₹60–72L/yr', keySkills: ['Data centre operations management (8MW+)', 'Uptime / SLA governance', 'NOC build-out', 'Tenant escalation management', 'Capacity planning'], notes: 'Senior operations lead for Building A as compute scales to 8MW. Manages DC technician team (R05, R11, R19), owns SLA performance across all colocation tenants, and leads 10MW expansion planning.' },
  { id: 'R17', title: 'Process Engineer — Minerals & Chemistry', department: 'Roborns Minerals', venture: 'Roborns', type: 'Full-time', status: 'on-hold', priority: 'high', targetStart: 'Q1 2028', location: 'Mangaluru (on-site)', phase: 'Y3 — Growth', salaryRange: '₹38–46L/yr', keySkills: ['Ion-exchange process optimisation', 'Chemical process engineering', 'Mineral purity grading (NaCl, Mg, KCl, Br)', 'LANXESS resin lifecycle management', 'Scale-up from pilot to full production'], notes: 'Owns Building C process optimisation as mineral output scales to commercial volumes. Works with LANXESS on resin regeneration cycles, grades mineral output to Tata Chemicals and GHCL specifications, and engineers the scale-up to 8 t/day NaCl yield.' },
  { id: 'R18', title: 'Procurement & Supply Chain Manager', department: 'Roborns Operations',  venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q2 2028', location: 'Mangaluru / Remote', phase: 'Y3 — Growth', salaryRange: '₹32–40L/yr', keySkills: ['Industrial procurement', 'Vendor management (Finolex, LANXESS, Alfa Laval, Ion Exchange India)', 'Spare parts inventory', 'CMMS / ERP', 'Membrane and filter contract management'], notes: 'Manages all consumable procurement — LANXESS resin replacement cycles, Alfa Laval gasket and plate maintenance contracts, Finolex pipe fittings, Ion Exchange India filter cartridges. Owns spares inventory and preventive maintenance scheduling.' },
  { id: 'R19', title: 'Data Centre Technician #3',        department: 'Roborns Compute',       venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q2 2028', location: 'Mangaluru (on-site)', phase: 'Y3 — Growth', salaryRange: '₹12–16L/yr', keySkills: ['Server rack operations', 'Immersion cooling maintenance', 'Shift coverage', 'Hardware incident response', 'Dielectric fluid monitoring'], notes: 'Third DC technician enabling full 3-shift rotation at 8MW capacity. Handles night shift alongside R05 and R11 under supervision of Head of DC Operations (R16).' },
  { id: 'R20', title: 'HR & Talent Manager',              department: 'Roborns Operations',    venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q1 2028', location: 'Mangaluru (on-site)', phase: 'Y3 — Growth', salaryRange: '₹28–35L/yr', keySkills: ['HR operations (22+ headcount)', 'Recruitment for technical roles', 'Payroll coordination', 'Performance management', 'Compliance (PF, ESI, labour law)'], notes: 'First dedicated HR hire as Roborns headcount reaches 22. Formalises recruitment process, handles PF / ESI compliance, manages onboarding for all site-based staff, and coordinates performance reviews with department heads.' },
  { id: 'R21', title: 'Site Security Guard — Shift A',   department: 'Roborns Operations',    venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q1 2028', location: 'Mangaluru (on-site)', phase: 'Y3 — Growth', salaryRange: '₹5–7L/yr',   keySkills: ['Industrial site security', 'CCTV monitoring', 'Visitor access control', 'Coastal facility protocols', 'Night shift coverage'], notes: 'Day-shift security for the coastal campus. Manages visitor gate, CCTV monitoring, and restricted-area access for the compute vault and marine intake zone.' },
  { id: 'R22', title: 'Site Security Guard — Shift B',   department: 'Roborns Operations',    venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q1 2028', location: 'Mangaluru (on-site)', phase: 'Y3 — Growth', salaryRange: '₹5–7L/yr',   keySkills: ['Industrial site security', 'Night shift coverage', 'Emergency response protocols', 'Access control', 'Coastal facility awareness'], notes: 'Night-shift security covering the full campus 24/7 alongside R21. Essential for protecting immersion tank infrastructure, marine intake, and Building C mineral inventory.' },

  // Y4 Mature — hire Q1–Q3 2029 (+6, cumulative 28)
  { id: 'R23', title: 'Head of Engineering & Utilities',  department: 'Roborns Engineering',   venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q1 2029', location: 'Mangaluru (on-site)', phase: 'Y4 — Mature', salaryRange: '₹65–80L/yr', keySkills: ['Utilities management (HT grid, solar, UPS)', 'Heat exchange systems at scale', 'Desalination plant engineering', 'Capital project management', 'Vendor SLA management'], notes: 'Senior engineering head overseeing all utilities — 10MW HT grid, solar, UPS, thermal loop, and MED plant. Acts as escalation point for Thermal Engineer (R02) and Electrical Engineer (R03). Leads capex planning for any Phase 2 expansion.' },
  { id: 'R24', title: 'Mineral Sales Manager',            department: 'Roborns Sales',         venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q1 2029', location: 'Mangaluru / Travel', phase: 'Y4 — Mature', salaryRange: '₹48–58L/yr', keySkills: ['Commodity chemical sales', 'NaCl / Mg(OH)₂ / KCl / Bromine markets', 'Offtake contract structuring', 'Tata Chemicals / GHCL / Chemspec account management', 'Export potential'], notes: 'Owns all mineral revenue at scale — manages offtake contracts with Tata Chemicals, GHCL, Nirma (salt), Chemspec (specialty). Targets ₹14 Cr mineral revenue in Y4. Also explores export opportunities for Mg(OH)₂ and bromine compounds.' },
  { id: 'R25', title: 'Data Centre Technician #4',        department: 'Roborns Compute',       venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q2 2029', location: 'Mangaluru (on-site)', phase: 'Y4 — Mature', salaryRange: '₹12–16L/yr', keySkills: ['Server rack operations', 'Immersion cooling at 10MW', 'Shift handover', 'Hardware incident response', 'Tenant cross-connect management'], notes: 'Fourth DC technician for full 4-shift rotation at 10MW capacity. Ensures continuous coverage without relying on overtime from existing technicians R05, R11, R19.' },
  { id: 'R26', title: 'NOC / Infrastructure Engineer',    department: 'Roborns Compute',       venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'high',     targetStart: 'Q1 2029', location: 'Mangaluru (on-site)', phase: 'Y4 — Mature', salaryRange: '₹32–40L/yr', keySkills: ['Network operations centre (NOC)', 'Monitoring (Grafana, Prometheus, Zabbix)', 'Incident triage and escalation', 'Uptime SLA tracking', 'On-call engineering'], notes: 'Builds and runs the Roborns NOC — monitoring dashboards for compute uptime, power draw, thermal loop temps, and water output. First point of escalation for 24/7 tenant SLA incidents. Reports to Head of DC Operations (R16).' },
  { id: 'R27', title: 'Environmental Compliance Specialist', department: 'Roborns Operations', venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q2 2029', location: 'Mangaluru (on-site)', phase: 'Y4 — Mature', salaryRange: '₹22–28L/yr', keySkills: ['CRZ renewal and annual audits', 'ZLD compliance reporting', 'Environmental impact assessments', 'Karnataka Pollution Control Board', 'Water discharge monitoring'], notes: 'Manages all ongoing environmental compliance at scale — annual CRZ condition reviews, ZLD discharge certificates, KSPCB returns, and environmental audit reports. Works with Karnataka Coastal Authority and KUWSDB on annual water offtake compliance.' },
  { id: 'R28', title: 'Desalination Plant Operator #3',   department: 'Roborns Water',         venture: 'Roborns', type: 'Full-time', status: 'on-hold',  priority: 'medium',   targetStart: 'Q2 2029', location: 'Mangaluru (on-site)', phase: 'Y4 — Mature', salaryRange: '₹8–11L/yr',  keySkills: ['MED plant operation', '150K L/day shift management', 'SCADA monitoring', 'Emergency shutdown', 'Mineral pre-concentration handover to Building C'], notes: 'Third operator to ensure full 3-shift round-the-clock coverage at 150K L/day water output. Handles shift overlap with Building C mineral operator (R10) for brine handover quality checks.' },
];

// ─── APPLICATIONS ─────────────────────────────────────────────────────────────

export type AppStatus = 'new' | 'screening' | 'interview' | 'offer' | 'hired' | 'rejected';

export interface Application {
  id:          string;
  name:        string;
  position:    string;
  positionId?: string;
  source:      string;
  date:        string;
  status:      AppStatus;
  notes:       string;
}

export const APPLICATIONS: Application[] = [
  {
    id: 'A01', name: 'Rahul Shetty', position: 'Site Operations Manager', positionId: 'R01',
    source: 'LinkedIn', date: '2026-05-20', status: 'screening',
    notes: '8 years industrial facility management in Mangaluru. Previously shift supervisor at MRPL (Mangalore Refinery). Strong MESCOM HT liaison background and hands-on CRZ coastal permit experience. Phone screen scheduled for 28 May 2026.',
  },
];

// ─── TRAINING ─────────────────────────────────────────────────────────────────

export interface TrainingItem {
  title:     string;
  category:  string;
  assignee:  string;
  status:    'completed' | 'in-progress' | 'planned';
  resource:  string;
  notes:     string;
}

export const TRAINING: TrainingItem[] = [
  { title: 'Dubai HoldCo structure deep-dive', category: 'Legal', assignee: 'Shawaz', status: 'in-progress', resource: 'DIFC legal counsel sessions', notes: 'Understanding free zone vs mainland, token issuance rules, DFSA requirements.' },
  { title: 'Desalination technology fundamentals', category: 'Engineering', assignee: 'Shawaz', status: 'in-progress', resource: 'MED/MSF technical papers, GEA Group documentation', notes: 'Multi-effect distillation system design principles for Roborns thermal model.' },
  { title: 'SEBI investment platform regulations', category: 'Legal', assignee: 'Shawaz', status: 'planned', resource: 'SEBI circular repository + legal counsel briefing', notes: 'Required before Franchiseen investor onboarding begins.' },
  { title: 'Matter protocol specification (v1.3)', category: 'Engineering', assignee: 'Shawaz', status: 'completed', resource: 'CSA Matter specification docs + GitHub', notes: 'Completed as part of Cuestay protocol spec. Foundation for hardware design.' },
  { title: 'Next.js App Router — advanced patterns', category: 'Engineering', assignee: 'Shawaz', status: 'completed', resource: 'Next.js 16 docs / in-practice (hq.codelude.com build)', notes: 'Server components, iron-session auth, route protection, dynamic rendering.' },
  { title: 'Chart.js v4 — React integration', category: 'Engineering', assignee: 'Shawaz', status: 'completed', resource: 'chart.js docs + useEffect pattern', notes: 'Used for Roborns financial model P&L chart in HQ dashboard.' },
  { title: 'Franchise industry landscape', category: 'Business', assignee: 'Shawaz', status: 'planned', resource: 'Franchise India / IFA resources / competitor research', notes: 'Needed before first franchise partner pitch. Understand industry terminology and norms.' },
  { title: 'DeFi protocol mechanics (GMX, dYdX)', category: 'Engineering', assignee: 'Shawaz', status: 'planned', resource: 'Protocol documentation + testnet usage', notes: 'Required for Dextrip DeFi integration phase.' },
];

// ─── ONBOARDING ───────────────────────────────────────────────────────────────

export interface OnboardingStep {
  day:      string;
  title:    string;
  category: string;
  items:    string[];
}

export const ONBOARDING_TEMPLATE: OnboardingStep[] = [
  { day: 'Day 1', title: 'Access & setup', category: 'Admin', items: ['Create Codelude email account (X@codelude.com)', 'Add to Google Workspace', 'GitHub organisation invite', 'HQ (hq.codelude.com) account created', 'WhatsApp group added', 'Password manager set up (1Password / Bitwarden)', '2FA enabled on all accounts'] },
  { day: 'Day 1–2', title: 'Context & orientation', category: 'Culture', items: ['Read the Codelude Handbook (hq.codelude.com/dashboard/handbook)', 'Review all five venture pages on codelude.com', 'Read through Plan and Strategy modules in HQ for your venture(s)', 'Meet founder 1:1 — 30 min overview call', 'Review current task list in HQ → Tasks'] },
  { day: 'Day 3–5', title: 'First contribution', category: 'Work', items: ['Identify first meaningful task from HQ → Tasks (venture-specific)', 'Set up local development environment (if engineering)', 'Review codebase for your venture (GitHub)', 'Submit first PR or document within 5 days of joining'] },
  { day: 'Week 2', title: 'Integration', category: 'Work', items: ['Attend first weekly check-in', 'Update at least one task to "in-progress" or "done"', 'Log first activity entry in HQ → Activity', 'Complete any role-specific training items in HQ → People → Training'] },
  { day: 'Day 30', title: '30-day review', category: 'Culture', items: ['1:1 with founder — what\'s working, what\'s not', 'Review OKRs for next 30 days', 'Confirm permanent tool access and revoke any temporary access', 'Share honest feedback on onboarding process'] },
];
